-- MySQL Script generated by MySQL Workbench
-- Wed Dec  4 21:23:10 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Proyecto_BD_Grupo1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Proyecto_BD_Grupo1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Proyecto_BD_Grupo1` DEFAULT CHARACTER SET utf8 ;
USE `Proyecto_BD_Grupo1` ;

-- -----------------------------------------------------
-- Table `Proyecto_BD_Grupo1`.`Solicitud`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto_BD_Grupo1`.`Solicitud` (
  `idSolicitud` INT NOT NULL AUTO_INCREMENT,
  `Fecha` DATE NULL,
  `Puesto_Solicitado` VARCHAR(45) NULL,
  `Sueldo` DECIMAL(10) NULL,
  PRIMARY KEY (`idSolicitud`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto_BD_Grupo1`.`Persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto_BD_Grupo1`.`Persona` (
  `Nombres` VARCHAR(45) NULL,
  `Apellido_Paterno` VARCHAR(45) NULL,
  `Apellido_Materno` VARCHAR(45) NULL,
  `Domicilio` VARCHAR(90) NULL,
  `Colonia` VARCHAR(90) NULL,
  `Codigo_Postal` DECIMAL(10) NULL,
  `Telefono_Fijo` DECIMAL(20) NULL,
  `Telefono_Movil` VARCHAR(20) NULL,
  `Lugar_De_Nacimiento` VARCHAR(200) NULL,
  `Vive_con` VARCHAR(100) NULL,
  `Estatura` DECIMAL(4) NULL,
  `Peso` DECIMAL(4) NULL,
  `Personas_que_dependen` VARCHAR(100) NULL,
  `Estado_Civil` VARCHAR(45) NULL,
  `Solicitud_idSolicitud` INT NOT NULL,
  INDEX `fk_Persona_Solicitud1_idx` (`Solicitud_idSolicitud` ASC),
  PRIMARY KEY (`Solicitud_idSolicitud`),
  CONSTRAINT `fk_Persona_Solicitud1`
    FOREIGN KEY (`Solicitud_idSolicitud`)
    REFERENCES `Proyecto_BD_Grupo1`.`Solicitud` (`idSolicitud`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto_BD_Grupo1`.`Documentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto_BD_Grupo1`.`Documentos` (
  `Licencia_de_conducir` VARCHAR(45) NULL,
  `Tipo_de_licencia` VARCHAR(45) NULL,
  `Pasaporte` VARCHAR(45) NULL,
  `Tipo_pasaporte` VARCHAR(45) NULL,
  `Solicitud_idSolicitud` INT NOT NULL,
  INDEX `fk_Documentos_Solicitud1_idx` (`Solicitud_idSolicitud` ASC),
  PRIMARY KEY (`Solicitud_idSolicitud`),
  CONSTRAINT `fk_Documentos_Solicitud1`
    FOREIGN KEY (`Solicitud_idSolicitud`)
    REFERENCES `Proyecto_BD_Grupo1`.`Solicitud` (`idSolicitud`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto_BD_Grupo1`.`Escolaridad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto_BD_Grupo1`.`Escolaridad` (
  `Escuela_o_Institucion` VARCHAR(60) NULL,
  `Educacion` VARCHAR(45) NULL,
  `Domicilio` VARCHAR(45) NULL,
  `Fecha_ingreso` DATE NULL,
  `Fecha_finalizacion` DATE NULL,
  `Certificado` VARCHAR(45) NULL,
  `Solicitud_idSolicitud` INT NOT NULL,
  INDEX `fk_Escolaridad_Solicitud1_idx` (`Solicitud_idSolicitud` ASC),
  PRIMARY KEY (`Solicitud_idSolicitud`),
  CONSTRAINT `fk_Escolaridad_Solicitud1`
    FOREIGN KEY (`Solicitud_idSolicitud`)
    REFERENCES `Proyecto_BD_Grupo1`.`Solicitud` (`idSolicitud`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto_BD_Grupo1`.`Familiares`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto_BD_Grupo1`.`Familiares` (
  `Nombres` VARCHAR(45) NULL,
  `vivo` DECIMAL(1) NULL,
  `finado` DECIMAL(1) NULL,
  `Domicilio` VARCHAR(45) NULL,
  `Ocupacion` VARCHAR(45) NULL,
  `Solicitud_idSolicitud` INT NOT NULL,
  INDEX `fk_Familiares_Solicitud1_idx` (`Solicitud_idSolicitud` ASC),
  PRIMARY KEY (`Solicitud_idSolicitud`),
  CONSTRAINT `fk_Familiares_Solicitud1`
    FOREIGN KEY (`Solicitud_idSolicitud`)
    REFERENCES `Proyecto_BD_Grupo1`.`Solicitud` (`idSolicitud`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Proyecto_BD_Grupo1`.`Habitos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Proyecto_BD_Grupo1`.`Habitos` (
  `Salud` VARCHAR(40) NULL,
  `Enfermedades` VARCHAR(400) NULL,
  `Deportes` VARCHAR(200) NULL,
  `Pasatiempos` VARCHAR(200) NULL,
  `Solicitud_idSolicitud` INT NOT NULL,
  INDEX `fk_Habitos_Solicitud1_idx` (`Solicitud_idSolicitud` ASC),
  PRIMARY KEY (`Solicitud_idSolicitud`),
  CONSTRAINT `fk_Habitos_Solicitud1`
    FOREIGN KEY (`Solicitud_idSolicitud`)
    REFERENCES `Proyecto_BD_Grupo1`.`Solicitud` (`idSolicitud`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
